language: go
go: 1.12.x
dist: trusty
os: linux

env:
- GO111MODULE=on

install:
- go get golang.org/x/lint/golint

addons:
  sonarcloud:
    organization: "gessnerfl-github"
    token:
      secure: "fv5LVtDkqMFT/H731gvenBfgo59mI7wjbA3J7eX9ZabkeLu5ZmtdhChFAJc05n46Olb1NI2fAmz6IqYw/TU41BmQE0Gapwdf3wxsvHGR/sC9kgH3dApktPD66uiY6OxikSjsPNUBVIVaqPoIKaxA0kt8613vG9oeyiBBqcfbLsrOkjZ1QtMRhnyMV+5Qx4ZK5/A7ICqUjumxlUaJG9mkmS27HcD5uPitVd2iKbKEPrBmqFhSVEwNryw7Ut0jOjYrvl2rMBNx85JT4rHO0MAM3An5hFUdlxRDGoiruwEWAvBQcnuEKG6V4rsamrO5CIXiE5IfMEAtwL+hLFMeiIJ/oAzojFoMBjoD8TqOJ8dlAyTNFpl3aoXgyEEAM3I5CfqzHNimNNEds8Vz5PGKVl5l3edu4tHkL5Ou7Slj7s/aHi10X+NvbnMv2EWjUeXVbJ8aVewm5Tz21P3f+K0p5VUhr3T3FT890DHkwr83oJpgxg81Ks55lDpYZ8e430XlVxdcI/8tslxSpa4RhlecQazSxVK6WRUbKCI/W9sIU0XEeXs+HO60c4cDCuEIkELNymQc6H/zKqLXz0FK4BHz9cTOX8x+OaKvKMK/X1WGZBlgnfb5kb52YvXyiZz01hD6scLHU73L61+2IucolEPW7SHbCeYZ+L14WIoJwRheRNFIhLg="

script:
- make ci

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "UA0A5ANtwrwdJgX8bzP25UNzpgtE5+BfAT4o0whSFe10W0PKmERjp2Imrt8TKszUgSbcq7UbDal9YNfnmmW1E/7mb12L5JZ/LJ5vB1B9XEqjqz04GOIsgQpjFxXGhBuKTXzVLh5JVcC4RUZSMnC/91KCHaYeoFmAARrl9zZC6wK6Ra6iMtbH0dCcZgaKOM6h+OA0d44nrSeXHg/0nbNBLtmwkVI3GCPydpKhuyjfCXfzLlnHKCJz09fhNZY8uh6GnYk3F0Tpd/8ZpHeqG1yRmHPT+DPDZ6Au9EpKbhI4KJgMNyyC+UogoFpeLY7w8v2JsV5qm4+T403tul/hhG35+2zPde/q00UwbERc3Q2g+wXjmlUCbS5N70td/67TejmxWEyEKHi2lS2WwXrNFz4uTVnJ1MUgSakA112z++7MLPeZ6leojTATs1oaziiAhFBdgbApz/JtgXjeVDHSp3Hd6nLqRyYczGMqh2c+DFDUlAQ2tovoCIlHOZHlq62JhIyxygaSFaqxqGBy3F3q429iDm6oWM6GrVPRXWoLIRbilvT8v1c9TzV4D8AqmHHscBiXoq15z+R+BEADYIxhs4fd3ISQBZ8u50Raxurh0Viv1Km2cgHw7XNDOkrjGm/bHoVITaT50JJ3xeDygI1Joi6X/SCRRAJdfaAYUCX97V7VuU4="
  file_glob: true
  file: output/terraform-provider-instana*.zip
  on:
    tags: true
    repo: gessnerfl/terraform-provider-instana