title: Terraform Provider Instana
lang: en
description: Terraform provider implementation for the Instana REST API.

remote_theme: rundocs/jekyll-rtd-theme

addons_branch: true

addons:
  - github
  - plugins

copyright:
  revision: true

readme_index:
  with_frontmatter: true