name: CI/CD

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.0'

    - name: Get version number
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags --match "v*" --always --dirty)

    - name: Run build
      run: go build . 

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      continue-on-error: true
      with:
        skip-cache: true
    
    - name: Run testing
      run: go test ./... -cover -coverprofile=coverage.out -json | tee unit-test-report.json

    - name: Run sonar
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      with:
        args: >
          -Dsonar.projectVersion=${{ steps.get_version.outputs.VERSION }}
  
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ contains(github.ref, 'refs/tags/v') && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0

      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}